services:
  vue-builder:
    build: .
    volumes:
      - ./dist:/app/dist-copy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - satsnet
    depends_on:
      - vue-builder

networks:
  satsnet:
    external: true
    name: satsnet